# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Felix.Zhu 成长日记
email: zhupengfei1995@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
    Felix.Zhu 的一个记录学习文档的地方.
github_username: Felix.Zhu
minimal_mistakes_skin: neon
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

collections:
    typescripts:
        output: true
        permalink: /typescripts/:name/
    crxs:
        output: true
        permalink: /crx/:name/

include:
    - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-gist
    - jekyll-feed
    - jemoji
    - jekyll-include-cache
    - jekyll-toc

author:
    name: "Felix.Zhu"
    avatar: "/assets/images/avator.JPG"
    bio: "Felix.Zhu's Blog"
    links:
        - label: "GitHub"
          icon: "fab fa-fw fa-github"
          url: "https://github.com/Felix-Prince"

footer:
    links:
        - label: "GitHub"
          icon: "fab fa-fw fa-github"
          url: "https://github.com/Felix-Prince"

defaults:
    # _posts
    - scope:
          path: ""
          type: posts
      values:
          layout: single
          author_profile: true
          read_time: true
          comments: true
          share: true
          related: true
    # typescripts
    - scope:
          path: ""
          type: typescripts
      values:
          layout: single
          author_profile: true
          read_time: true
          comments: true
          share: true
          related: true
    # crxs
    - scope:
          path: ""
          type: crxs
      values:
          layout: single
          author_profile: true
          read_time: true
          comments: true
          share: true
          related: true
    # _pages
    - scope:
          path: "_pages"
          type: pages
      values:
          layout: single
          author_profile: true
# category_archive:
#     type: liquid
#     path: /categories/
# tag_archive:
#     type: liquid
#     path: /tags/
